spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev    #开发环境
  application:
    name: microservicecloud-config-zfl-dev
---
spring:
  profiles: text #测试环境
  application:
    name: microservicecloud-config-zfl-text
# 请保留UTF-8格式